- name: start a MongoDB exporter container
  docker_container:
    name: percona-mongodb-exporter
    image: kofonfor/percona_mongodb_exporter
    state: started
    recreate: yes
    restart_policy: always
    read_only: yes
    exposed_ports:
      - 9216
    ports:
      - "9216:9216"
    command:
      - "-mongodb.uri={{ mongodb_exporter_mongodb_uri }}"
      - "-collect.collection"
      - "-collect.database"
      - "-collect.indexusage"
      - "-collect.topmetrics"
